{% set name = "oscan" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oscan-{{ version }}.tar.gz
  sha256: 0012794f9ede6e603e769841eb9ce6a3c5b1afb65fb4d663094e20aa2fa2d0eb

build:
  entry_points:
    - oscan = oscan.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - oscan
  commands:
    - pip check
    - oscan --help
    # Skip for now, test suite empty
    # - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/oscan
  summary: Scanner used to build Pyrustic Backstage
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
